server:
  port: 8091

spring:
  application:
    name: xxl-job-admin


### mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

management:
  health:
    mail:
      enabled: false
  server:
    servlet:
      context-path: /actuator
