server:
  port: 8090
  servlet:
    context-path: /project

spring:
  application:
    name: project
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 250MB

file:
  upload-dir: ./upload

### mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

